name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for proverance data generation
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        shell: bash

      - uses: nrwl/nx-set-shas@v4

      - name: Print Environment Info
        run: npx nx report
        shell: bash
      - run: npx nx affected -t lint test build e2e-ci

      - name: Publish packages
        run: npx nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVERANCE: true
