name: Release

on:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  PRIMARY_NODE_VERSION: 20
  # This increases the verbosity of the logs for everything, including Nx Cloud, but will hopefully surface more info about recent lint failures
  NX_VERBOSE_LOGGING: true

defaults:
  run:
    shell: bash

permissions:
  actions: read
  contents: read

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # needed for proverance data generation

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          # node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - name: Print Environment Info
        run: npx nx report

      - name: Build
        run: npx nx run-many --t build --parallel 2

      - name: test
        run: npx nx run-many -t test --parallel 2

      - name: Release
        run: |
          git config user.name "Release Bot"
          git config user.email "<>"
          npx nx release --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVERANCE: true
